#!/usr/bin/env bash

database="${DIRENV_DIR:1}/dealapp.db"
file="${DIRENV_DIR:1}/scripts/property_types.csv"
curl https://dealapp.sa/api/property-types?type=ALL | jq -r '.data[] | "\(._id),\(.propertyType_ar),\(.propertyType),\(.category)"' >> "$file"
sqlite3 "$database" ".import --csv ${file} property_types"
rm -f "$file"
